apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.gitlabDockerConfigJson }}
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  annotations:
      app.gitlab.com/app: {{ .Values.gitlabCiProjectPath }}
      app.gitlab.com/env: {{ .Values.gitlabCiProjectEnvironment }}
  name: {{ .Release.Name }}-gitlab-registry-secret