apiVersion: v1
kind: Secret
metadata:
    annotations:
        app.gitlab.com/app: {{ .Values.gitlabCiProjectPath }}
        app.gitlab.com/env: {{ .Values.gitlabCiProjectEnvironment }}
    name: {{ .Values.name }}-secrets
    namespace: {{ .Values.deploymentNamespace }}
    labels:
        app: {{ .Values.name }}
type: Opaque
data:
    appDbConnectionString: {{ .Values.appDbConnectionString }}
    sqlDbName: {{ .Values.sqlDbName }}
    sqlDbUser: {{ .Values.sqlDbUser }}
    sqlDbPassword: {{ .Values.sqlDbPassword }}
    auth0ManagementUrl: {{ .Values.auth0ManagementUrl }}
    auth0ManagementClientId: {{ .Values.auth0ManagementClientId }}
    auth0ManagementClientSecret: {{ .Values.auth0ManagementClientSecret }}
    auth0ManagementAudience: {{ .Values.auth0ManagementAudience }}
    auth0Tenant: {{ .Values.auth0Tenant }}
    smtpServerDomain: {{ .Values.smtpServerDomain }}
    smtpServerPort: {{ .Values.smtpServerPort }}
    smtpServerEmailAddress: {{ .Values.smtpServerEmailAddress }}
    smtpServerEmailPassword: {{ .Values.smtpServerEmailPassword }}
    applicationServiceAccount: {{ .Values.applicationServiceAccount }}