apiVersion: v1
kind: Deployment
metadata:
    # annotations:
        # app.gitlab.com/app: {{ .Values.gitlabCiProjectPath }}
        # app.gitlab.com/env: {{ .Values.gitlabCiProjectEnvironment }}
    name: {{ .Release.Name }}
    namespace: {{ .Values.deploymentNamespace }}
    labels:
        app: {{ .Release.Name }}
spec:
    replicas: {{ .Values.replicas }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}
    template:
        metadata:
            annotations:
                app.gitlab.com/app: {{ .Values.gitlabCiProjectPath }}
                app.gitlab.com/env: {{ .Values.gitlabCiProjectEnvironment }}
            labels:
                app: {{ .Release.Name }}
        spec:
            imagePullSecrets:
                - name: gitlab-registry
            containers:
                -   name: {{ .Release.Name }}
                    image: {{ .Values.image }}
                    imagePullPolicy: Always
                    ports:
                        - containerPort: 80
                    env:
                    -   name: ASPNETCORE_ENVIRONMENT
                        value: {{ .Values.netCoreEnvironment }}
                    -   name: ASPNET_DB_CONNECTIONSTRING
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: appDbConnectionString
                    -   name: MYSQL_DB_HOST
                        value: 127.0.0.1:3306
                    -   name: MYSQL_DB_NAME
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: sqlDbName
                    -   name: MYSQL_DB_USER
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: sqlDbUser
                    -   name: MYSQL_DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: sqlDbPassword
                    -   name: MANAGEMENTURL_ENVIRONMENT
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: auth0ManagementUrl
                    -   name: CLIENT_ID_ENVIRONMENT
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: auth0ManagementClientId
                    -   name: CLIENT_SECRET_ENVIRONMENT
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: auth0ManagementClientSecret
                    -   name: AUDIENCE_ENVIRONMENT
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: auth0ManagementAudience
                    -   name: DOMAINNAME_ENVIRONMENT
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: auth0Tenant
                    -   name: PRIMARY_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: smtpServerDomain
                    -   name: PRIMARY_PORT
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: smtpServerPort
                    -   name: USERNAME_EMAIL
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: smtpServerEmailAddress
                    -   name: USERNAME_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: smtpServerEmailPassword
                    -   name: LANGUAGE
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Release.Name }}-secrets
                                key: applicationLanguage
            -   name: devenv-mysql
                image: mysql:5.6
                env:
                -   name: MYSQL_DATABASE
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-secrets
                            key: sqlDbName
                -   name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-secrets
                            key: sqlDbPassword
                -   name: MYSQL_USER
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-secrets
                            key: sqlDbUser
                -   name: MYSQL_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-secrets
                            key: sqlDbPassword