apiVersion: v1
kind: Secret
metadata:
    # annotations:
        # app.gitlab.com/app: {{ .Values.gitlabCiProjectPath }}
        # app.gitlab.com/env: {{ .Values.gitlabCiProjectEnvironment }}
    name: {{ .Release.Name }}-secrets
    namespace: {{ .Values.deploymentNamespace }}
    labels:
        app: {{ .Release.Name }}
data:
    { appDbConnectionString: "{{ printf "server=127.0.0.1;port=3306;user id=%s;password=%s;database=%s;SslMode=none;Convert Zero Datetime=true;Charset=utf8;" .Values.sqlDbUser .Values.sqlDbPassword .Values.sqlDbName }}"}
    sqlDbName: {{ .Values.sqlDbName }}
    sqlDbUser: {{ .Values.sqlDbUser }}
    sqlDbPassword: {{ .Values.sqlDbPassword }}
    auth0ManagementUrl: {{ .Values.auth0ManagementUrl }}
    auth0ManagementClientId: {{ .Values.auth0ManagementClientId }}
    auth0ManagementClientSecret: {{ .Values.auth0ManagementClientSecret }}
    auth0ManagementAudience: {{ .Values.auth0ManagementAudience }}
    auth0Tenant: {{ .Values.auth0Tenant }}
    smtpServerDomain: {{ .Values.smtpServerDomain }}
    smtpServerPort: {{ .Values.smtpServerPort }}
    smtpServerEmailAddress: {{ .Values.smtpServerEmailAddress }}
    smtpServerEmailPassword: {{ .Values.smtpServerEmailPassword }}
    applicationLanguage: {{ .Values.applicationLanguage }}